export const pokemonTypes = [
  "grass",
  "fire",
  "water",
  "bug",
  "normal",
  "poison",
  "electric",
  "ground",
  "fairy",
  "fighting",
  "psychic",
  "rock",
  "ghost",
  "ice",
  "dragon",
  "dark",
  "steel",
  "flying",
];

export const typeColorMap = {
  grass: { bg: "bg-green-500", border: "border-green-400" },
  fire: { bg: "bg-red-500", border: "border-red-400" },
  water: { bg: "bg-blue-500", border: "border-blue-400" },
  bug: { bg: "bg-lime-500", border: "border-lime-400" },
  normal: { bg: "bg-gray-400", border: "border-gray-300" },
  poison: { bg: "bg-purple-600", border: "border-purple-500" },
  electric: { bg: "bg-yellow-400", border: "border-yellow-300" },
  ground: { bg: "bg-amber-700", border: "border-amber-600" },
  fairy: { bg: "bg-pink-400", border: "border-pink-300" },
  fighting: { bg: "bg-orange-700", border: "border-orange-600" },
  psychic: { bg: "bg-pink-600", border: "border-pink-500" },
  rock: { bg: "bg-stone-500", border: "border-stone-400" },
  ghost: { bg: "bg-indigo-800", border: "border-indigo-700" },
  ice: { bg: "bg-cyan-300", border: "border-cyan-200" },
  dragon: { bg: "bg-violet-700", border: "border-violet-600" },
  dark: { bg: "bg-zinc-800", border: "border-zinc-700" },
  steel: { bg: "bg-slate-500", border: "border-slate-400" },
  flying: { bg: "bg-sky-400", border: "border-sky-300" },
};
